### ISSUE TITLE
Removing canceled shows from schedule.

### ISSUE THREAD

**Issue by jjok** [mcflynnthm/com.johnrflynn.thefest10#3]
Need an effective way of removing canceled shows from user's schedule.

**Comment by jjok** [comment]
How does the app know about cancelled shows? Do you have to add a new version of the database and let the app do an update?
What's the issue here? You must be able to do a check when the app starts up, or something?

**Comment by mcflynnthm** [comment]
Basically, it'll know because the newer version of the data won't have said show in it. I'm not sure if you've checked out the XML file for the schedule data at all, but shows are a subset of each artist. I'm using the same data as Rob, the guy that made the iPhone Fest app last year. (with his blessing, of course!)
The user's schedule db just tracks, IIRC, the _id of the shows they're going to, so removing the show with that _id if it's not found in the new data and then checking for it in the user db (and removing if necessary) is probably the way to go.
